In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
salmon_data = pd.read_pickle('salmon_data.pkl')
salmon_data.head()

,Species,Length.Measurement.Type,sampleYear,ASLProjectType,LocationID,sampleDate,Length,Weight,Sex,Salt.Water.Age,...,Flag,Gear,SASAP.Region,LocationUnique,DistrictID,Sub.DistrictID,Stat.area,Lat,Lon,AWC_CODE
0,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,NaN,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN
1,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,NaN,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN
2,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,NaN,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN
3,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,3.0,...,NaN,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN
4,chinook,length not taken,1992.0,commercial catch,Affleck Canal/Spanish Is/Louise Cove,1992-03-31,NaN,NaN,examined but did not identify,4.0,...,NaN,troll,Southeast,Affleck Canal/Spanish Is/Louise Cove-commercia...,105.0,10.0,10510.0,NaN,NaN,NaN

In [3]:
salmon_data.shape

(14347461, 27)